CREATE TABLE nation( N_NATIONKEY INTEGER NOT NULL, N_NAME CHAR(25) NOT NULL, N_REGIONKEY INTEGER NOT NULL, N_COMMENT VARCHAR(152));

CREATE TABLE region(R_REGIONKEY INTEGER NOT NULL, R_NAME CHAR(25) NOT NULL,  R_COMMENT VARCHAR(152));

CREATE TABLE supplier( S_SUPPKEY INTEGER NOT NULL, S_NAME CHAR(25) NOT NULL, S_ADDRESS VARCHAR(40) NOT NULL, S_NATIONKEY INTEGER NOT NULL, S_PHONE CHAR(15) NOT NULL, S_ACCTBAL FLOAT NOT NULL, S_COMMENT VARCHAR(101) NOT NULL);

CREATE TABLE customer(C_CUSTKEY INTEGER NOT NULL,C_NAME VARCHAR(25) NOT NULL, C_ADDRESS VARCHAR(40) NOT NULL, C_NATIONKEY INTEGER NOT NULL, C_PHONE CHAR(15) NOT NULL, C_ACCTBAL FLOAT NOT NULL, C_MKTSEGMENT CHAR(10) NOT NULL, C_COMMENT VARCHAR(117) NOT NULL);

CREATE TABLE orders( O_ORDERKEY INTEGER NOT NULL,  O_CUSTKEY INTEGER NOT NULL,  O_ORDERSTATUS CHAR(1) NOT NULL,  O_TOTALPRICE FLOAT NOT NULL,  O_ORDERDATE DATETIME NOT NULL,  O_ORDERPRIORITY CHAR(15) NOT NULL,  O_CLERK CHAR(15) NOT NULL, O_SHIPPRIORITY INTEGER NOT NULL, O_COMMENT VARCHAR(79) NOT NULL);

CREATE TABLE lineitem( L_ORDERKEY INTEGER NOT NULL, L_PARTKEY INTEGER NOT NULL, L_SUPPKEY INTEGER NOT NULL, L_LINENUMBER INTEGER NOT NULL, L_QUANTITY FLOAT NOT NULL, L_EXTENDEDPRICE FLOAT NOT NULL, L_DISCOUNT FLOAT NOT NULL,  L_TAX FLOAT NOT NULL,  L_RETURNFLAG CHAR(1) NOT NULL, L_LINESTATUS CHAR(1) NOT NULL, L_SHIPDATE DATETIME NOT NULL, L_COMMITDATE DATETIME NOT NULL, L_RECEIPTDATE DATETIME NOT NULL, L_SHIPINSTRUCT CHAR(25) NOT NULL, L_SHIPMODE CHAR(10) NOT NULL, L_COMMENT VARCHAR(44) NOT NULL);

CREATE TABLE part(  P_PARTKEY INTEGER NOT NULL, P_NAME VARCHAR(55) NOT NULL, P_MFGR CHAR(25) NOT NULL, P_BRAND CHAR(10) NOT NULL, P_TYPE VARCHAR(25) NOT NULL, P_SIZE INTEGER NOT NULL, P_CONTAINER CHAR(10) NOT NULL,  P_RETAILPRICE FLOAT NOT NULL,  P_COMMENT VARCHAR(23) NOT NULL);

begin; 
load /home/ziyang/works/db2024/DB2024/tmp/benchmark_data/nation.tbl into nation; 
load /home/ziyang/works/db2024/DB2024/tmp/benchmark_data/supplier.tbl into supplier; 
load /home/ziyang/works/db2024/DB2024/tmp/benchmark_data/customer.tbl into customer; 
load /home/ziyang/works/db2024/DB2024/tmp/benchmark_data/region.tbl into region; 
load /home/ziyang/works/db2024/DB2024/tmp/benchmark_data/orders.tbl into orders; 
load /home/ziyang/works/db2024/DB2024/tmp/benchmark_data/part.tbl into part; 
load /home/ziyang/works/db2024/DB2024/tmp/benchmark_data/lineitem.tbl into lineitem; 
commit;


select * from concurrency_test where id > 2 and id < 4;     
insert into concurrency_test values (3, 'xiaoyang', 100.0);